services:
  postgres:
    image: postgres:14.5
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - database.env

  rails_api:
    container_name: client_api
    image: ruby:3.1.0
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "bin/setup && rails s -b 0.0.0.0"
    volumes:
      - ./client-api:/app
      - gem-cache:/usr/local/bundle
    env_file:
      - database.env
    depends_on:
      - postgres

  react_app:
    image: node:18
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./client-app:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    command: ['bash', '-c', 'yarn && yarn dev --host']
    depends_on:
      - postgres

volumes:
  database:
  yarn-cache:
  gem-cache: